#!/bin/bash

python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out
python3 run.py squareroot 8 >> squareroot8.out

python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out
python3 run.py squareroot 16 >> squareroot16.out

python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out
python3 run.py squareroot 24 >> squareroot24.out

python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
python3 run.py squareroot 32 >> squareroot32.out
