#!/bin/bash

python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py supremacy 16 >> supremacy.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py qaoa 16 >> qaoa.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py squareroot 16 >> squareroot.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py qft 16 >> qft.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py adder 16 >> adder.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out
python3 run.py bv 16 >> bv.out

