#!/bin/bash

python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out
python3 run.py supremacy 8 >> supremacy8.out

python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out
python3 run.py supremacy 16 >> supremacy16.out

python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out
python3 run.py supremacy 24 >> supremacy24.out

python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
python3 run.py supremacy 32 >> supremacy32.out
